### ISSUE TITLE
Bug with `type: 'loading'`

### ISSUE THREAD

**Issue by mrleblanc101** [jerrywu001/vue3-toastify#70]
Using `type: 'loading'` doesn't produce the same thing as `toast.loading(...)`
```
$toast(AppToast, {
    type: 'loading',
    contentProps: {
        content: 'This is a toast message',
    },
});
$toast.loading(AppToast, {
    contentProps: {
        content: 'This is a toast message',
    },
});
```
![Screenshot 2024-12-17 at 10 33 30 PM](https://github.com/user-attachments/assets/55f3fc9a-9a86-415b-8462-d5837a0d3ee6)

**Comment by jerrywu001** [comment]
Please provide the code of AppToast

**Comment by mrleblanc101** [comment]
@jerrywu001 Currently there is pretty much nothing.
It's basically straight from the doc:
```
<script lang="ts">
import type { ToastOptions } from 'vue3-toastify';
import type { PropType } from 'vue';

export default {
    props: {
        closeToast: Function as PropType<(e?: MouseEvent) => void>,
        toastProps: Object as PropType<ToastOptions>,
        contentProps: Object as PropType<ToastOptions>,
    },
};
</script>

<template>
    <div>
        <!-- <pre>{{ contentProps }}</pre> -->
        <button
            @click="
                ($event) => {
                    closeToast && closeToast($event);
                }
            "
        >
            Click me to close toast
        </button>
    </div>
</template>
```

**Comment by jerrywu001** [comment]
Fixed with 0.2.8

**Comment by mrleblanc101** [comment]
@jerrywu001 The toast is still transparent on my side:
![Screenshot 2024-12-18 at 10 32 37 AM](https://github.com/user-attachments/assets/71ef5013-312c-48ba-b15d-d38762cc5e01)

**Comment by mrleblanc101** [comment]
@jerrywu001 I've tracked the issue.
The `colored` theme does not have a default background.
And there is no background specified for the `loading` type:

```css
.#{$rt-namespace}__toast {
  &-theme--dark {
    background: var(--toastify-color-dark); // <-- default for dark
    color: var(--toastify-text-color-dark);
  }

  &-theme--light {
    background: var(--toastify-color-light); // <-- default for light
    color: var(--toastify-text-color-light);
  }
  // <-- missing default for colored
  &-theme--colored#{&}--default {
    background: var(--toastify-color-light);
    color: var(--toastify-text-color-light);
  }
  &-theme--colored#{&}--info {
    color: var(--toastify-text-color-info);
    background: var(--toastify-color-info);
  }
  &-theme--colored#{&}--success {
    color: var(--toastify-text-color-success);
    background: var(--toastify-color-success);
  }
  &-theme--colored#{&}--warning {
    color: var(--toastify-text-color-warning);
    background: var(--toastify-color-warning);
  }
  &-theme--colored#{&}--error {
    color: var(--toastify-text-color-error);
    background: var(--toastify-color-error);
  }
}
```
Otherwise, we need to change:
```css
  &-theme--colored#{&}--default,
  &-theme--colored#{&}--loading {
    background: var(--toastify-color-light);
    color: var(--toastify-text-color-light);
  }
  ```
